import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

void test("recent chat list keeps shared routing and adds agent labels", async () => {
  const source = await readFile(new URL("./recent-chat-list.tsx", import.meta.url), "utf8");

  assert.ok(source.includes("isAgentsUiEnabled"));
  assert.ok(
    source.includes("pathOfConversation"),
    "expected recent chat links to be generated by the shared conversation path helper",
  );
  assert.ok(source.includes("BotIcon"));
  assert.ok(source.includes("conversation.agent_name"));
});
