import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

void test("recent chat list hides itself on disabled agents routes via the shared feature flag", async () => {
  const source = await readFile(new URL("./recent-chat-list.tsx", import.meta.url), "utf8");

  assert.ok(source.includes("isAgentsUiEnabled"));
  assert.ok(
    source.includes('return isAgentsUiEnabled() ? <BffRecentChatList pathname={pathname} /> : null;'),
    "expected agents-route recent chat visibility to be controlled by the shared feature flag",
  );
  assert.ok(
    source.includes("pathOfConversation"),
    "expected recent chat links to be generated by the shared conversation path helper",
  );
});
